// HLTV flag images carry a code in their src, e.g. /img/static/flags/30x20/DK.gif
// or /img/static/flags/300x200/EU.png. Newer HLTV markup drops those images from
// the clipboard, but the copied text and flag titles carry the country name, so
// this module resolves both codes and names to an emoji flag.

// Region names from CLDR (generated with Intl.DisplayNames), keys normalized
// with normalizeCountryName below.
const COUNTRY_CODES: Record<string, string> = {
  "afghanistan": "AF",
  "aland islands": "AX",
  "albania": "AL",
  "algeria": "DZ",
  "american samoa": "AS",
  "andorra": "AD",
  "angola": "AO",
  "anguilla": "AI",
  "antarctica": "AQ",
  "antigua and barbuda": "AG",
  "argentina": "AR",
  "armenia": "AM",
  "aruba": "AW",
  "ascension island": "AC",
  "australia": "AU",
  "austria": "AT",
  "azerbaijan": "AZ",
  "bahamas": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belarus": "BY",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bermuda": "BM",
  "bhutan": "BT",
  "bolivia": "BO",
  "bosnia and herzegovina": "BA",
  "botswana": "BW",
  "bouvet island": "BV",
  "brazil": "BR",
  "british indian ocean territory": "IO",
  "british virgin islands": "VG",
  "brunei": "BN",
  "bulgaria": "BG",
  "burkina faso": "BF",
  "burma": "MM",
  "burundi": "BI",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "canary islands": "IC",
  "cape verde": "CV",
  "caribbean netherlands": "BQ",
  "cayman islands": "KY",
  "central african republic": "CF",
  "ceuta and melilla": "EA",
  "chad": "TD",
  "chile": "CL",
  "china": "CN",
  "christmas island": "CX",
  "clipperton island": "CP",
  "cocos keeling islands": "CC",
  "colombia": "CO",
  "comoros": "KM",
  "congo": "CD",
  "congo brazzaville": "CG",
  "congo democratic republic of": "CD",
  "congo kinshasa": "CD",
  "cook islands": "CK",
  "costa rica": "CR",
  "cote d ivoire": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "curacao": "CW",
  "cyprus": "CY",
  "czech republic": "CZ",
  "czechia": "CZ",
  "democratic republic of the congo": "CD",
  "denmark": "DK",
  "diego garcia": "DG",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "dr congo": "CD",
  "east timor": "TL",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "eswatini": "SZ",
  "ethiopia": "ET",
  "europe": "EU",
  "european union": "EU",
  "falkland islands": "FK",
  "faroe islands": "FO",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "french guiana": "GF",
  "french polynesia": "PF",
  "french southern territories": "TF",
  "gabon": "GA",
  "gambia": "GM",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "gibraltar": "GI",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "guadeloupe": "GP",
  "guam": "GU",
  "guatemala": "GT",
  "guernsey": "GG",
  "guinea": "GN",
  "guinea bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "heard and mcdonald islands": "HM",
  "honduras": "HN",
  "hong kong": "HK",
  "hong kong sar china": "HK",
  "hungary": "HU",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "isle of man": "IM",
  "israel": "IL",
  "italy": "IT",
  "ivory coast": "CI",
  "jamaica": "JM",
  "japan": "JP",
  "jersey": "JE",
  "jordan": "JO",
  "kazakhstan": "KZ",
  "kenya": "KE",
  "kiribati": "KI",
  "korea": "KR",
  "kosovo": "XK",
  "kuwait": "KW",
  "kyrgyzstan": "KG",
  "laos": "LA",
  "latvia": "LV",
  "lebanon": "LB",
  "lesotho": "LS",
  "liberia": "LR",
  "libya": "LY",
  "liechtenstein": "LI",
  "lithuania": "LT",
  "luxembourg": "LU",
  "macao sar china": "MO",
  "macau": "MO",
  "macedonia": "MK",
  "madagascar": "MG",
  "malawi": "MW",
  "malaysia": "MY",
  "maldives": "MV",
  "mali": "ML",
  "malta": "MT",
  "marshall islands": "MH",
  "martinique": "MQ",
  "mauritania": "MR",
  "mauritius": "MU",
  "mayotte": "YT",
  "mexico": "MX",
  "micronesia": "FM",
  "moldova": "MD",
  "monaco": "MC",
  "mongolia": "MN",
  "montenegro": "ME",
  "montserrat": "MS",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "myanmar burma": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "nepal": "NP",
  "netherlands": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "niger": "NE",
  "nigeria": "NG",
  "niue": "NU",
  "norfolk island": "NF",
  "north korea": "KP",
  "north macedonia": "MK",
  "northern mariana islands": "MP",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "palestinian territories": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "pitcairn islands": "PN",
  "poland": "PL",
  "portugal": "PT",
  "puerto rico": "PR",
  "qatar": "QA",
  "reunion": "RE",
  "romania": "RO",
  "russia": "RU",
  "rwanda": "RW",
  "saint kitts and nevis": "KN",
  "saint lucia": "LC",
  "saint vincent and the grenadines": "VC",
  "samoa": "WS",
  "san marino": "SM",
  "sao tome and principe": "ST",
  "sark": "CQ",
  "saudi arabia": "SA",
  "senegal": "SN",
  "serbia": "RS",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "sint maarten": "SX",
  "slovakia": "SK",
  "slovenia": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south georgia and south sandwich islands": "GS",
  "south korea": "KR",
  "south sudan": "SS",
  "spain": "ES",
  "sri lanka": "LK",
  "st barthelemy": "BL",
  "st helena": "SH",
  "st kitts and nevis": "KN",
  "st lucia": "LC",
  "st martin": "MF",
  "st pierre and miquelon": "PM",
  "st vincent and grenadines": "VC",
  "sudan": "SD",
  "suriname": "SR",
  "svalbard and jan mayen": "SJ",
  "swaziland": "SZ",
  "sweden": "SE",
  "switzerland": "CH",
  "syria": "SY",
  "taiwan": "TW",
  "tajikistan": "TJ",
  "tanzania": "TZ",
  "thailand": "TH",
  "the netherlands": "NL",
  "timor leste": "TL",
  "togo": "TG",
  "tokelau": "TK",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "tristan da cunha": "TA",
  "tunisia": "TN",
  "turkey": "TR",
  "turkiye": "TR",
  "turkmenistan": "TM",
  "turks and caicos islands": "TC",
  "tuvalu": "TV",
  "u s outlying islands": "UM",
  "u s virgin islands": "VI",
  "uganda": "UG",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united nations": "UN",
  "united states": "US",
  "united states virgin islands": "VI",
  "uruguay": "UY",
  "us virgin islands": "VI",
  "uzbekistan": "UZ",
  "vanuatu": "VU",
  "vatican city": "VA",
  "venezuela": "VE",
  "vietnam": "VN",
  "wallis and futuna": "WF",
  "western sahara": "EH",
  "yemen": "YE",
  "zambia": "ZM",
  "zimbabwe": "ZW",
};

// Regions without an ISO code, and GB subdivision flags. Keys normalized.
const SPECIAL_NAME_FLAGS: Record<string, string> = {
  world: "🌍",
  international: "🌍",
  cis: "🌍",
  africa: "🌍",
  asia: "🌏",
  oceania: "🌏",
  "north america": "🌎",
  "south america": "🌎",
  england: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  scotland: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};

const SPECIAL_CODE_FLAGS: Record<string, string> = {
  WORLD: "🌍",
  CIS: "🌍",
  "GB-ENG": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  "GB-SCT": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
  "GB-WLS": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};

const REGIONAL_INDICATOR_OFFSET = 0x1f1e6 - "A".charCodeAt(0);

function normalizeCountryName(value: string): string {
  return value
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9 ]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}

/**
 * Resolves a country name as HLTV prints it ("Brazil", "Türkiye", "Europe")
 * to a flag code usable with flagEmoji. Special regions with no ISO code
 * ("World", "Scotland") resolve to a name key handled by flagEmoji directly.
 */
export function countryCode(name: string | undefined): string | null {
  const normalized = name ? normalizeCountryName(name) : "";
  if (!normalized) return null;
  if (COUNTRY_CODES[normalized]) return COUNTRY_CODES[normalized];
  if (SPECIAL_NAME_FLAGS[normalized]) return normalized;
  return null;
}

export function flagEmoji(code: string | undefined): string | null {
  const trimmed = code?.trim() ?? "";
  if (!trimmed) return null;
  const upper = trimmed.toUpperCase();
  if (SPECIAL_CODE_FLAGS[upper]) return SPECIAL_CODE_FLAGS[upper];
  if (/^[A-Z]{2}$/.test(upper)) {
    return String.fromCodePoint(
      ...[...upper].map((letter) => letter.charCodeAt(0) + REGIONAL_INDICATOR_OFFSET),
    );
  }
  return SPECIAL_NAME_FLAGS[normalizeCountryName(trimmed)] ?? null;
}
